### ISSUE TITLE
Random freezes in AR scene (Unity 2018.3.b9)

### ISSUE THREAD

**Issue by nilsk123** [Unity-Technologies/arfoundation-samples#67]
The arcamera and entire scene will freeze at random after a couple of minutes, but sometimes after seconds.

The latest updates fixed the freeze on switching scene, but this one persists. Nothing of real interest is outputed to the log other than `To Debug, enable the define: TLA_DEBUG_STACK_LEAK in ThreadsafeLinearAllocator.cpp. This will output the callstacks of the leaked allocations`

Xcode doesn't register a crash, the app just sits there frozen.

Testing on iPhone SE, latest beta, all packages up to date

https://pastebin.com/ZwUSLTkm

**Comment by tdmowrer** [comment]
There's a known issue on iOS which can hang randomly. It should be fixed in 2018.3 (you can try a beta now if you like). I haven't seen the `JobTempAlloc` issue, though. Are you running one of the sample scenes in this repo, or is this something different?

**Comment by nilsk123** [comment]
Hi Tim, thanks for the response. This still happens when using the latest 2018.3.b9. Is there any kind of logging i can send you to narrow this down?

As for the jobtempalloc issue, the internet is full of reports about it starting some months, but i dont think its arfoundation related.

This is an app were working on, will try to reproduce using an 'empty' samples project.

**Comment by tdmowrer** [comment]
> Is there any kind of logging i can send you to narrow this down?
Yes, if you can pause the app in Xcode and look at the callstacks and tell me if you see something like [this one](https://issuetracker.unity3d.com/issues/hang-on-ios-using-arkit-xr-plugin).

**Comment by nilsk123** [comment]
I've fixed the JobTempAlloc issue by disabling casting shadows on my directional light (disabling receive shadow on meshes helps too), and haven't since seen the crash.

**Comment by sergiosolorzano** [comment]
I had the same issue, app would crash and couldn't upload to app store, disabling casting shadows on dir light as suggested by @nilsk123 worked for me too

**Comment by sergiosolorzano** [comment]
finding continued behaviour with arfoundation preview 22, logging here https://github.com/Unity-Technologies/arfoundation-samples/issues/85
cheers, Sergio
